import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>What is HTML?</h1>
      <h2>What is HTML?</h2>
      <h3>What is HTML?</h3>
      <h4>What is HTML?</h4>
      <h5>What is HTML?</h5>
      <p>
        HTML is an acronym which stands for Hyper Text Markup Language which is
        used for creating web pages and web applications. Let's see what is
        meant by Hypertext Markup Language, and Web page. Hyper Text: HyperText
        simply means "Text within Text." A text has a link within it, is a
        hypertext. Whenever you click on a link which brings you to a new
        webpage, you have clicked on a hypertext. HyperText is a way to link two
        or more web pages (HTML documents) with each other.
      </p>
      <p>
        HTML is an acronym which stands for Hyper Text Markup Language which is
        used for creating web pages and web applications. Let's see what is
        meant by Hypertext Markup Language, and Web page. Hyper Text: HyperText
        simply means "Text within Text." A text has a link within it, is a
        hypertext. Whenever you click on a link which brings you to a new
        webpage, you have clicked on a hypertext. HyperText is a way to link two
        or more web pages (HTML documents) with each other.
      </p>
      <p>
        HTML is an acronym which stands for Hyper Text Markup Language which is
        used for creating web pages and web applications. Let's see what is
        meant by Hypertext Markup Language, and Web page. Hyper Text: HyperText
        simply means "Text within Text." A text has a link within it, is a
        hypertext. Whenever you click on a link which brings you to a new
        webpage, you have clicked on a hypertext. HyperText is a way to link two
        or more web pages (HTML documents) with each other.
      </p>
    </div>
  );
}
